# Generated by Django 5.0.2 on 2024-03-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acheteur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=10)),
                ('prenom', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('CIN', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='medicament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('prix', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('dateExpiration', models.DateField()),
                ('stockDisponible', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pharmacien',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('sexe', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=100)),
                ('salaire', models.IntegerField()),
            ],
        ),
    ]
